import { describe, it, expect } from "vitest"
import { renderDealenzPdf } from "./pdf"

const CONTENT = `# Proposal

## Business Profile
Service Provider: Acme Studio

## Scope
- Build a homepage
- Build a contact page

1. Review and approve
2. Sign the agreement

Payment due {{payment_date}}.

---
`

describe("DealenzDocument", () => {
  it("renders a real PDF from the shared markdown AST", async () => {
    const buffer = await renderDealenzPdf({
      letterhead: { name: "Acme Studio", lines: ["Lagos, Nigeria"] },
      content: CONTENT,
      footerNote: "Generated by Dealenz",
    })
    expect(buffer.subarray(0, 5).toString("utf8")).toBe("%PDF-")
    expect(buffer.length).toBeGreaterThan(2000)
  })

  it("renders without a letterhead", async () => {
    const buffer = await renderDealenzPdf({ letterhead: null, content: "# Title\n\nBody.", footerNote: "Dealenz" })
    expect(buffer.subarray(0, 5).toString("utf8")).toBe("%PDF-")
  })

  it("renders pricing tables", async () => {
    const buffer = await renderDealenzPdf({
      letterhead: null,
      content: "# Proposal\n\n| Item | Price |\n| --- | ---: |\n| Homepage | $500 |\n| Contact page | $250 |",
      footerNote: "Dealenz",
    })
    expect(buffer.subarray(0, 5).toString("utf8")).toBe("%PDF-")
    expect(buffer.length).toBeGreaterThan(1500)
  })
})
