import { SectionWrapper, Heading, BodyText } from "@/components/landing/primitives"

const docs = [
  {
    name: "Proposal",
    description: "Sets expectations before the engagement starts, so scope discussions happen before the contract, not during the project.",
    imgSrc: "/placeholder-proposal.png",
    imgAlt: "Proposal document preview",
  },
  {
    name: "Scope of Work",
    description: "Defines exactly what is included and what is not. You reference this when a client asks to add one more thing.",
    imgSrc: "/placeholder-sow.png",
    imgAlt: "Scope of work preview",
  },
  {
    name: "Contract",
    description: "Covers payment, IP ownership, revision limits, and termination. The terms are calibrated to what the risk report found.",
    imgSrc: "/placeholder-contract.png",
    imgAlt: "Contract preview",
  },
  {
    name: "Deliverables Checklist",
    description: "A live checklist for the active engagement. Each item is either in scope, out of scope, or a change order.",
    imgSrc: "/placeholder-checklist.png",
    imgAlt: "Checklist preview",
  },
]



export function DocumentsSection() {
  return (
    <SectionWrapper width="xwide" className="py-14 sm:py-20">
      <Heading>Four documents from every deal.</Heading>
      <div className="mt-8 flex flex-col sm:flex-row sm:items-start sm:gap-12">
        <div className="sm:w-1/2">
          <div className="overflow-hidden rounded-lg border border-border/40 shadow-sm">
            <img
              src="/protection-package.png"
              alt="Generated protection package"
              className="block h-auto w-full object-contain"
            />
          </div>
        </div>
        <div className="sm:w-1/2 mt-4 sm:mt-0">
          <p className="text-sm sm:text-base leading-relaxed text-muted-foreground">
            Each deal generates a complete protection package: a proposal, scope of work, contract, and deliverables checklist. Every document builds on the one before it, so nothing gets contradicted.
          </p>
        </div>
      </div>
      <div className="mt-8 grid gap-6 sm:grid-cols-2">
        {docs.map((d) => (
          <div key={d.name} className="rounded-xl border border-border/60 bg-card p-6">
            <h3 className="text-base font-semibold">{d.name}</h3>
            <BodyText muted className="mt-2">{d.description}</BodyText>
            <div className="mt-4 overflow-hidden rounded-lg border border-border/40 bg-muted/30">
              <img
                src={d.imgSrc}
                alt={d.imgAlt}
                className="block h-auto w-full"
              />
            </div>
          </div>
        ))}
      </div>
      <BodyText variant="small" muted className="mt-4 max-w-2xl">
        Documents are generated by AI and should be reviewed before use. Dealenz is not a law firm and this is not legal advice.
      </BodyText>
    </SectionWrapper>
  )
}
