import { describe, it, expect } from "vitest"
import { registeredVerticalKeys, verticalForDealType } from "./index"

describe("vertical dispatcher", () => {
  it("resolves freelance, lease, purchase_sale, employment, generic, founder, and partnership packs and nothing else", () => {
    expect(registeredVerticalKeys().sort()).toEqual(["employment", "founder", "freelance", "generic", "lease", "partnership", "purchase_sale"])
    const freelance = verticalForDealType("freelance")
    expect(freelance?.key).toBe("freelance")
    expect(typeof freelance?.deriveFacts).toBe("function")
    expect(typeof freelance?.registerPack).toBe("function")
    expect(typeof freelance?.selectCandidates).toBe("function")
    const lease = verticalForDealType("lease")
    expect(lease?.key).toBe("lease")
    expect(typeof lease?.deriveFacts).toBe("function")
    expect(typeof lease?.registerPack).toBe("function")
    expect(typeof lease?.selectCandidates).toBe("function")
    const purchaseSale = verticalForDealType("purchase_sale")
    expect(purchaseSale?.key).toBe("purchase_sale")
    expect(typeof purchaseSale?.deriveFacts).toBe("function")
    expect(typeof purchaseSale?.registerPack).toBe("function")
    expect(typeof purchaseSale?.selectCandidates).toBe("function")
    const employment = verticalForDealType("employment")
    expect(employment?.key).toBe("employment")
    expect(typeof employment?.deriveFacts).toBe("function")
    expect(typeof employment?.registerPack).toBe("function")
    expect(typeof employment?.selectCandidates).toBe("function")
    const generic = verticalForDealType("generic")
    expect(generic?.key).toBe("generic")
    expect(typeof generic?.deriveFacts).toBe("function")
    expect(typeof generic?.registerPack).toBe("function")
    expect(typeof generic?.selectCandidates).toBe("function")
    const founder = verticalForDealType("founder")
    expect(founder?.key).toBe("founder")
    expect(typeof founder?.deriveFacts).toBe("function")
    expect(typeof founder?.registerPack).toBe("function")
    expect(typeof founder?.selectCandidates).toBe("function")
    const partnership = verticalForDealType("partnership")
    expect(partnership?.key).toBe("partnership")
    expect(typeof partnership?.deriveFacts).toBe("function")
    expect(typeof partnership?.registerPack).toBe("function")
    expect(typeof partnership?.selectCandidates).toBe("function")
  })

  it("returns null for unknown deal types", () => {
    expect(verticalForDealType("unknown")).toBeNull()
    expect(verticalForDealType("")).toBeNull()
  })
})
