import type { Rule } from "@/lib/rules/schema"

export const PROPOSAL_RULES: Rule[] = [
  {
    ruleKey: "proposal-objective-coverage",
    version: 1,
    title: "Every important objective has a response",
    description: "Each client objective in the plan should be addressed by proposed work or deliverable",
    status: "active",
    priority: 90,
    category: "requirement",
    scope: { operations: ["proposal"] },
    condition: { field: "facts.proposal.objectiveCount", op: "gt", value: 0 },
    fireOn: true,
    finding: { summary: "Objective without response", severity: "material", guidance: "Add a proposed response for each objective" },
    authority: { kind: "product_policy", note: "Proposal standard: objectives map to responses" },
  },
  {
    ruleKey: "proposal-deliverable-rationale",
    version: 1,
    title: "Major deliverable has rationale",
    description: "Each deliverable should explain why it matters to the client",
    status: "active",
    priority: 85,
    category: "requirement",
    scope: { operations: ["proposal"] },
    condition: { field: "facts.proposal.deliverableCount", op: "gt", value: 0 },
    fireOn: true,
    finding: { summary: "Deliverable without rationale", severity: "material" },
    authority: { kind: "product_policy", note: "Every deliverable needs why it matters" },
  },
  {
    ruleKey: "proposal-next-step",
    version: 1,
    title: "Proposal has concrete next step",
    description: "Proposal must have a next step",
    status: "active",
    priority: 95,
    category: "requirement",
    scope: { operations: ["proposal"] },
    condition: { field: "facts.proposal.hasNextStep", op: "eq", value: false },
    fireOn: true,
    finding: { summary: "Missing next step", severity: "material", guidance: "Add a concrete next step" },
    authority: { kind: "product_policy", note: "Proposal needs next step" },
  },
  {
    ruleKey: "proposal-assumptions-visible",
    version: 1,
    title: "Material assumptions surfaced",
    description: "When unresolved items exist, assumptions should be visible",
    status: "active",
    priority: 70,
    category: "requirement",
    scope: { operations: ["proposal"] },
    condition: { field: "facts.proposal.unresolvedCount", op: "gt", value: 0 },
    fireOn: true,
    finding: { summary: "Unresolved material information not surfaced as assumption", severity: "attention" },
    authority: { kind: "product_policy", note: "Assumptions visible where material" },
  },
  {
    ruleKey: "proposal-no-guarantee",
    version: 1,
    title: "No unsupported guarantees",
    description: "Benefits must not be presented as guarantees unless supported",
    status: "active",
    priority: 80,
    category: "protection",
    scope: { operations: ["proposal"] },
    condition: { field: "facts.proposal.hasGuarantee", op: "eq", value: true },
    fireOn: true,
    finding: { summary: "Unsupported guarantee language", severity: "material", guidance: "Rephrase as expected outcome unless guarantee is supported" },
    authority: { kind: "product_policy", note: "Do not guarantee outcomes without support" },
  },
  {
    ruleKey: "proposal-commercial-consistency",
    version: 1,
    title: "Commercial terms consistent with scope",
    description: "Price/timeline must not contradict scope",
    status: "active",
    priority: 75,
    category: "consistency",
    scope: { operations: ["proposal"] },
    condition: { field: "facts.proposal.commercialInconsistent", op: "eq", value: true },
    fireOn: true,
    finding: { summary: "Commercial inconsistency", severity: "material" },
    authority: { kind: "product_policy", note: "Commercial must match scope/timeline" },
  },
]

export function proposalRules(): Rule[] {
  return PROPOSAL_RULES
}
