import { NextRequest, NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"
import { renderDealenzPdf, type PdfLetterhead } from "@/lib/documents/pdf"

// Owner PDF download: the artifact the reader shows, as a file. Free by
// design — generation already charged; downloading is not new work. Renders
// server-side from the same markdown AST as the screen, so WYSIWYG holds.

export const dynamic = "force-dynamic"

function safeFilename(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "document"
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ auditId: string }> }) {
  const { auditId } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 })

  const versionId = new URL(req.url).searchParams.get("versionId")

  const { data: audit } = await supabase
    .from("audits")
    .select("id, title")
    .eq("id", auditId)
    .eq("user_id", user.id)
    .maybeSingle()
  if (!audit) return NextResponse.json({ success: false, error: "Deal not found" }, { status: 404 })

  let query = supabase
    .from("document_versions")
    .select("id, document_type, version_number, content")
    .eq("audit_id", auditId)
    .eq("user_id", user.id)
    .order("version_number", { ascending: false })
    .limit(1)
  if (versionId) query = query.eq("id", versionId)
  const { data: version } = await query.maybeSingle()
  const row = version as { id: string; document_type: string; version_number: number; content: string } | null
  if (!row || !row.content?.trim()) {
    return NextResponse.json({ success: false, error: "No document version to export yet." }, { status: 404 })
  }

  const { data: profile } = await supabase
    .from("business_profiles")
    .select("business_name, address, city, country, email, phone, website")
    .eq("user_id", user.id)
    .maybeSingle()
  const p = profile as {
    business_name?: string | null; address?: string | null; city?: string | null; country?: string | null;
    email?: string | null; phone?: string | null; website?: string | null;
  } | null
  const letterhead: PdfLetterhead | null = p?.business_name
    ? {
      name: p.business_name,
      lines: [
        [p.address, p.city, p.country].filter(Boolean).join(", "),
        [p.email, p.phone, p.website].filter(Boolean).join(" · "),
      ].filter((l) => l.length > 0),
    }
    : null

  let buffer: Buffer
  try {
    buffer = await renderDealenzPdf({
      letterhead,
      content: row.content,
      footerNote: `Generated by Dealenz · ${new Date().toISOString().slice(0, 10)}`,
    })
  } catch {
    return NextResponse.json({ success: false, error: "We couldn't build that PDF. Please try again." }, { status: 500 })
  }

  const filename = `${safeFilename((audit as { title?: string }).title ?? row.document_type)}-${row.document_type}-v${row.version_number}.pdf`
  const body = new Uint8Array(buffer)
  return new NextResponse(body, {
    status: 200,
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `attachment; filename="${filename}"`,
      "content-length": String(body.byteLength),
    },
  })
}
